version: '3.7'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: classroom
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker_cache/mysql:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3307:3306"

  app:
    build:
      context: ./docker
      dockerfile: dockerfile
    depends_on:
      - mysql
    user: "1000:1000"
    working_dir: /var/www/html
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html

  npm:
    image: node:14
    entrypoint: ['npm']
    user: "1000:1000"
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./:/src
    working_dir: /src
    environment:
      - NODE_ENV=development

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
        API_URL: http://localhost/api/swagger
